<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Modelo para detección de fraude | Detección de Fraude en Transacciones de Pago de la Unión Europea.</title>
  <meta name="description" content="Se presenta el análisis exploratorio inicial del dataset escogido sobre transacciones bancarias presentadas por los bancos centrales de la Unión Europea" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Modelo para detección de fraude | Detección de Fraude en Transacciones de Pago de la Unión Europea." />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Se presenta el análisis exploratorio inicial del dataset escogido sobre transacciones bancarias presentadas por los bancos centrales de la Unión Europea" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Modelo para detección de fraude | Detección de Fraude en Transacciones de Pago de la Unión Europea." />
  
  <meta name="twitter:description" content="Se presenta el análisis exploratorio inicial del dataset escogido sobre transacciones bancarias presentadas por los bancos centrales de la Unión Europea" />
  

<meta name="author" content="Tiffany Mendoza S. y Sergio Rada" />


<meta name="date" content="2026-05-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="análisis-exploratorio-bivariado.html"/>
<link rel="next" href="conclusión-1.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Payments Transactions EU</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Análisis Exploratorio de Datos</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contexto-inicial"><i class="fa fa-check"></i>Contexto inicial</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#objetivo-del-an%C3%A1lisis"><i class="fa fa-check"></i>Objetivo del análisis</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#objetivo-general"><i class="fa fa-check"></i>Objetivo General</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#objetivos-espec%C3%ADficos"><i class="fa fa-check"></i>Objetivos Específicos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#metodolog%C3%ADa"><i class="fa fa-check"></i>Metodología</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#origen-y-descripci%C3%B3n-del-dataset"><i class="fa fa-check"></i>Origen y descripción del dataset</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#variables-preprocesamiento-y-divisi%C3%B3n-de-los-datos"><i class="fa fa-check"></i>Variables, Preprocesamiento y División de los Datos</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#modelos-estrategias-de-balanceo-y-optimizaci%C3%B3n-de-hiperpar%C3%A1metros"><i class="fa fa-check"></i>Modelos, Estrategias de Balanceo y Optimización de Hiperparámetros</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#m%C3%A9tricas-de-evaluaci%C3%B3n-comparaci%C3%B3n-estad%C3%ADstica-e-interpretabilidad"><i class="fa fa-check"></i>Métricas de Evaluación, Comparación Estadística e Interpretabilidad</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#caracterizaci%C3%B3n-general"><i class="fa fa-check"></i>Caracterización general</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#diccionario-de-columnas"><i class="fa fa-check"></i>Diccionario de columnas</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#comprobaci%C3%B3n-de-columna-repetidas"><i class="fa fa-check"></i>Comprobación de columna repetidas</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#columnas-a-utilizar"><i class="fa fa-check"></i>Columnas a utilizar</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dataframe-resultante"><i class="fa fa-check"></i>Dataframe resultante</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#identificaci%C3%B3n-de-valores-faltantes"><i class="fa fa-check"></i>Identificación de valores faltantes</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="analisis-univariado.html"><a href="analisis-univariado.html"><i class="fa fa-check"></i><b>2</b> Analisis Univariado</a>
<ul>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#variable-objetivo-tipo_fraude"><i class="fa fa-check"></i>Variable objetivo: tipo_fraude</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#variables-caracter%C3%ADsticas-categ%C3%B3ricas"><i class="fa fa-check"></i>Variables Características Categóricas</a>
<ul>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#clave"><i class="fa fa-check"></i>clave</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#frecuencia"><i class="fa fa-check"></i>frecuencia</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#pais_origen"><i class="fa fa-check"></i>pais_origen</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#pais_destino"><i class="fa fa-check"></i>pais_destino</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#tipo_trx"><i class="fa fa-check"></i>tipo_trx</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#tipo_psp"><i class="fa fa-check"></i>tipo_psp</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#unidad"><i class="fa fa-check"></i>unidad</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#anio"><i class="fa fa-check"></i>anio</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#tipo_monto"><i class="fa fa-check"></i>tipo_monto</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#decimales"><i class="fa fa-check"></i>decimales</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#descripcion"><i class="fa fa-check"></i>descripcion</a></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#multiplicador_unidad"><i class="fa fa-check"></i>multiplicador_unidad</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#variables-caracter%C3%ADsticas-num%C3%A9ricas"><i class="fa fa-check"></i>Variables Características Numéricas</a>
<ul>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#monto"><i class="fa fa-check"></i>monto</a></li>
<li class="chapter" data-level="2.0.1" data-path="analisis-univariado.html"><a href="analisis-univariado.html#tratamiento-de-datos-faltantes-para-la-variable-monto"><i class="fa fa-check"></i><b>2.0.1</b> Tratamiento de datos faltantes para la variable “monto”</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="analisis-univariado.html"><a href="analisis-univariado.html#predicciones-vs-valores-reales"><i class="fa fa-check"></i>Predicciones vs Valores reales</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html"><i class="fa fa-check"></i><b>3</b> Análisis Exploratorio Bivariado</a>
<ul>
<li class="chapter" data-level="3.1" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#an%C3%A1lisis-de-la-variable-de-respuesta-frente-a-las-variables-num%C3%A9ricas"><i class="fa fa-check"></i><b>3.1</b> Análisis de la variable de respuesta frente a las variables numéricas</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#gr%C3%A1fico-multiple"><i class="fa fa-check"></i><b>3.1.1</b> Gráfico multiple</a></li>
<li class="chapter" data-level="3.1.2" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#comparaci%C3%B3n-de-ambas-muestras"><i class="fa fa-check"></i><b>3.1.2</b> Comparación de ambas muestras</a></li>
<li class="chapter" data-level="3.1.3" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#prueba-de-normalidad"><i class="fa fa-check"></i><b>3.1.3</b> Prueba de normalidad</a></li>
<li class="chapter" data-level="3.1.4" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#test-de-wilcoxon"><i class="fa fa-check"></i><b>3.1.4</b> Test de Wilcoxon</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#an%C3%A1lisis-de-la-variable-de-respuesta-frente-a-las-variables-categ%C3%B3ricas-independientes."><i class="fa fa-check"></i><b>3.2</b> Análisis de la variable de respuesta frente a las variables categóricas independientes.</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#variable-clave"><i class="fa fa-check"></i><b>3.2.1</b> Variable clave</a></li>
<li class="chapter" data-level="3.2.2" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#variable-frecuencia"><i class="fa fa-check"></i><b>3.2.2</b> Variable frecuencia</a></li>
<li class="chapter" data-level="3.2.3" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#variable-pais_origen"><i class="fa fa-check"></i><b>3.2.3</b> Variable pais_origen</a></li>
<li class="chapter" data-level="3.2.4" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#variable-pais_destino"><i class="fa fa-check"></i><b>3.2.4</b> Variable pais_destino</a></li>
<li class="chapter" data-level="3.2.5" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#variable-tipo_trx"><i class="fa fa-check"></i><b>3.2.5</b> Variable tipo_trx</a></li>
<li class="chapter" data-level="3.2.6" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#variable-tipo_psp"><i class="fa fa-check"></i><b>3.2.6</b> Variable tipo_psp</a></li>
<li class="chapter" data-level="3.2.7" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#variable-unidad"><i class="fa fa-check"></i><b>3.2.7</b> Variable unidad</a></li>
<li class="chapter" data-level="3.2.8" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#variable-anio-a%C3%B1o"><i class="fa fa-check"></i><b>3.2.8</b> Variable anio (año)</a></li>
<li class="chapter" data-level="3.2.9" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#variable-tipo_monto"><i class="fa fa-check"></i><b>3.2.9</b> Variable tipo_monto</a></li>
<li class="chapter" data-level="3.2.10" data-path="análisis-exploratorio-bivariado.html"><a href="análisis-exploratorio-bivariado.html#variable-descripcion"><i class="fa fa-check"></i><b>3.2.10</b> Variable descripcion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html"><i class="fa fa-check"></i><b>4</b> Modelo para detección de fraude</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#preprocesamiento"><i class="fa fa-check"></i><b>4.1</b> Preprocesamiento</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#feature-engineering"><i class="fa fa-check"></i><b>4.1.1</b> Feature Engineering</a></li>
<li class="chapter" data-level="4.1.2" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#selecci%C3%B3n-de-variable-para-el-modelado"><i class="fa fa-check"></i><b>4.1.2</b> Selección de variable para el modelado</a></li>
<li class="chapter" data-level="4.1.3" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#pre-procesamiento-con-columntransformer"><i class="fa fa-check"></i><b>4.1.3</b> Pre-procesamiento con ColumnTransformer</a></li>
<li class="chapter" data-level="4.1.4" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#split-de-los-datos"><i class="fa fa-check"></i><b>4.1.4</b> Split de los datos</a></li>
<li class="chapter" data-level="4.1.5" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#validaci%C3%B3n-cruzada"><i class="fa fa-check"></i><b>4.1.5</b> Validación cruzada</a></li>
<li class="chapter" data-level="4.1.6" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#pipeline-para-el-entrenamiento-de-modelos"><i class="fa fa-check"></i><b>4.1.6</b> Pipeline para el entrenamiento de modelos</a></li>
<li class="chapter" data-level="4.1.7" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#estructura-del-pipeline"><i class="fa fa-check"></i><b>4.1.7</b> Estructura del Pipeline</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#resultados"><i class="fa fa-check"></i><b>4.2</b> Resultados</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#mejores-par%C3%A1metros-de-cada-modelo"><i class="fa fa-check"></i><b>4.2.1</b> Mejores parámetros de cada modelo</a></li>
<li class="chapter" data-level="4.2.2" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#comparaci%C3%B3n-de-las-t%C3%A9cnicas-de-balanceo"><i class="fa fa-check"></i><b>4.2.2</b> Comparación de las técnicas de balanceo</a></li>
<li class="chapter" data-level="4.2.3" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#interpretabilidad-con-lime"><i class="fa fa-check"></i><b>4.2.3</b> Interpretabilidad con LIME</a></li>
<li class="chapter" data-level="4.2.4" data-path="modelo-para-detección-de-fraude.html"><a href="modelo-para-detección-de-fraude.html#conclusi%C3%B3n"><i class="fa fa-check"></i><b>4.2.4</b> Conclusión</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="conclusión-1.html"><a href="conclusión-1.html"><i class="fa fa-check"></i><b>5</b> Conclusión</a>
<ul>
<li class="chapter" data-level="5.1" data-path="conclusión-1.html"><a href="conclusión-1.html#referencias"><i class="fa fa-check"></i><b>5.1</b> Referencias</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Detección de Fraude en Transacciones de Pago de la Unión Europea.</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelo-para-detección-de-fraude" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Modelo para detección de fraude<a href="modelo-para-detección-de-fraude.html#modelo-para-detecci%C3%B3n-de-fraude" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En esta sección se explicará la creación del modelo de detección de fraude hecho en python. En este caso, no se realizará el entrenamiento porque R no cuenta con las suficientes librerias para ello.</p>
<p>Se desea elegir un modelo que prediga el fraude en transacciones, por tanto, la variable objetivo será “tipo_fruade”. Por tanto, se realizará un análisis comparativo entre los diferentes algoritmos de Machine Learning que abarcan desde enfoques lineales, como la Regresión Logística con penalizaciones L1 (Lasso) y L2 (Ridge), hasta Random Forest y XGBoost. Dado que el dataset presenta un desbalanceo crítico, integraré técnicas de balanceo de carga mediante el ajuste de pesos de clase (Class Weights) y métodos de sobremuestreo sintético como SMOTE/ADASYN, asegurando que el aprendizaje no se sesgue hacia la clase mayoritaria y se maximice la detección de fraudes reales.</p>
<p>Para garantizar la robustez de los resultados, optimizaré los hiperparámetros de cada arquitectura (incluyendo KNN, Naïve Bayes y SVM) mediante RandomizedSearchCV, buscando el equilibrio óptimo entre precisión y sensibilidad (Recall), usando la métrica de F1-Score para el entrenamiento y mostrando al final todas las métricas en una tabla. Finalmente, el modelo con mejor desempeño será sometido a un análisis de interpretabilidad con LIME, permitiendo identificar las variables clave que disparan las alertas de fraude, proporcionando así una solución no solo predictiva, sino también explicable.</p>
<div id="preprocesamiento" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Preprocesamiento<a href="modelo-para-detección-de-fraude.html#preprocesamiento" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="feature-engineering" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Feature Engineering<a href="modelo-para-detección-de-fraude.html#feature-engineering" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En esta parte del preprocesamiento se buscará limpiar y transformar los datos brutos en variables inteligentes para que el modelo aprenda mejor.<br />
* Variable monto</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="modelo-para-detección-de-fraude.html#cb90-1" tabindex="-1"></a><span class="co"># Número de Fraudes de monto menor a 0</span></span>
<span id="cb90-2"><a href="modelo-para-detección-de-fraude.html#cb90-2" tabindex="-1"></a><span class="fu">nrow</span>(datos2[datos2<span class="sc">$</span>monto_final <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> datos2<span class="sc">$</span>tipo_fraude <span class="sc">==</span> <span class="st">&quot;con fraude&quot;</span>, ])</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="modelo-para-detección-de-fraude.html#cb92-1" tabindex="-1"></a><span class="co"># Número de fraudes con monto igual a 0</span></span>
<span id="cb92-2"><a href="modelo-para-detección-de-fraude.html#cb92-2" tabindex="-1"></a><span class="fu">nrow</span>(datos2[datos2<span class="sc">$</span>monto_final <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> datos2<span class="sc">$</span>tipo_fraude <span class="sc">==</span> <span class="st">&quot;con fraude&quot;</span>, ])</span></code></pre></div>
<pre><code>## [1] 228</code></pre>
<p>Véase que los montos negativos no tienen observaciones donde haya fraude, pero si transacciones donde el monto es 0, esto puede deberse por ejemplos a pruebas del banco de intentos de autorización y demás. Por tanto, se filtrará el dataset para quedarnos con observaciones con monto mayores o iguales a 0, luego se usará el Log1 para comprimir los montos muy grandes.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="modelo-para-detección-de-fraude.html#cb94-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> datos2 <span class="sc">%&gt;%</span></span>
<span id="cb94-2"><a href="modelo-para-detección-de-fraude.html#cb94-2" tabindex="-1"></a>  <span class="fu">filter</span>(monto_final <span class="sc">&gt;=</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb94-3"><a href="modelo-para-detección-de-fraude.html#cb94-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">monto_final =</span> <span class="fu">log1p</span>(monto_final))</span>
<span id="cb94-4"><a href="modelo-para-detección-de-fraude.html#cb94-4" tabindex="-1"></a></span>
<span id="cb94-5"><a href="modelo-para-detección-de-fraude.html#cb94-5" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb94-6"><a href="modelo-para-detección-de-fraude.html#cb94-6" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb94-7"><a href="modelo-para-detección-de-fraude.html#cb94-7" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>##      monto             decimales     multiplicador_unidad  monto_final       
##  Min.   :0.000e+00   Min.   :2.000   Min.   :1.000        Min.   : 0.000000  
##  1st Qu.:0.000e+00   1st Qu.:3.000   1st Qu.:6.000        1st Qu.: 0.003473  
##  Median :1.000e+00   Median :3.000   Median :6.000        Median : 0.892335  
##  Mean   :6.440e+05   Mean   :2.914   Mean   :5.567        Mean   : 2.906014  
##  3rd Qu.:1.570e+02   3rd Qu.:3.000   3rd Qu.:6.000        3rd Qu.: 4.947607  
##  Max.   :2.951e+09   Max.   :3.000   Max.   :6.000        Max.   :21.805269  
##  NA&#39;s   :143569</code></pre>
<p>La única variable que se trató fue monto porque presenta mucho sesgo y outliers, por tanto, a los modelos se le dificulta predecir si presentamos así esta variable.</p>
</div>
<div id="selección-de-variable-para-el-modelado" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Selección de variable para el modelado<a href="modelo-para-detección-de-fraude.html#selecci%C3%B3n-de-variable-para-el-modelado" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Aquí se seleccionarán las variables que serán utilizadas en el modelado. Se excluyen variables como “clave”, “decimales”, “descripción” y “multiplicador_unidad” que realmente no aportan nada al modelo.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="modelo-para-detección-de-fraude.html#cb96-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb96-2"><a href="modelo-para-detección-de-fraude.html#cb96-2" tabindex="-1"></a></span>
<span id="cb96-3"><a href="modelo-para-detección-de-fraude.html#cb96-3" tabindex="-1"></a>FEATURES_CAT <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb96-4"><a href="modelo-para-detección-de-fraude.html#cb96-4" tabindex="-1"></a>  <span class="st">&quot;frecuencia&quot;</span>,</span>
<span id="cb96-5"><a href="modelo-para-detección-de-fraude.html#cb96-5" tabindex="-1"></a>  <span class="st">&quot;pais_origen&quot;</span>,</span>
<span id="cb96-6"><a href="modelo-para-detección-de-fraude.html#cb96-6" tabindex="-1"></a>  <span class="st">&quot;pais_destino&quot;</span>,</span>
<span id="cb96-7"><a href="modelo-para-detección-de-fraude.html#cb96-7" tabindex="-1"></a>  <span class="st">&quot;tipo_trx&quot;</span>,</span>
<span id="cb96-8"><a href="modelo-para-detección-de-fraude.html#cb96-8" tabindex="-1"></a>  <span class="st">&quot;tipo_psp&quot;</span>,</span>
<span id="cb96-9"><a href="modelo-para-detección-de-fraude.html#cb96-9" tabindex="-1"></a>  <span class="st">&quot;unidad&quot;</span>,</span>
<span id="cb96-10"><a href="modelo-para-detección-de-fraude.html#cb96-10" tabindex="-1"></a>  <span class="st">&quot;tipo_monto&quot;</span></span>
<span id="cb96-11"><a href="modelo-para-detección-de-fraude.html#cb96-11" tabindex="-1"></a>)</span>
<span id="cb96-12"><a href="modelo-para-detección-de-fraude.html#cb96-12" tabindex="-1"></a></span>
<span id="cb96-13"><a href="modelo-para-detección-de-fraude.html#cb96-13" tabindex="-1"></a>FEATURES_ALL <span class="ot">&lt;-</span> <span class="fu">c</span>(FEATURES_CAT, <span class="st">&quot;monto_final&quot;</span>)</span>
<span id="cb96-14"><a href="modelo-para-detección-de-fraude.html#cb96-14" tabindex="-1"></a>TARGET <span class="ot">&lt;-</span> <span class="st">&quot;tipo_fraude_bin&quot;</span></span>
<span id="cb96-15"><a href="modelo-para-detección-de-fraude.html#cb96-15" tabindex="-1"></a></span>
<span id="cb96-16"><a href="modelo-para-detección-de-fraude.html#cb96-16" tabindex="-1"></a></span>
<span id="cb96-17"><a href="modelo-para-detección-de-fraude.html#cb96-17" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb96-18"><a href="modelo-para-detección-de-fraude.html#cb96-18" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tipo_fraude_bin =</span> <span class="fu">as.integer</span>(<span class="fu">tolower</span>(tipo_fraude) <span class="sc">==</span> <span class="st">&quot;con fraude&quot;</span>))</span>
<span id="cb96-19"><a href="modelo-para-detección-de-fraude.html#cb96-19" tabindex="-1"></a></span>
<span id="cb96-20"><a href="modelo-para-detección-de-fraude.html#cb96-20" tabindex="-1"></a>datos <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb96-21"><a href="modelo-para-detección-de-fraude.html#cb96-21" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(FEATURES_ALL), <span class="fu">all_of</span>(TARGET)) <span class="sc">%&gt;%</span></span>
<span id="cb96-22"><a href="modelo-para-detección-de-fraude.html#cb96-22" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="sc">!!</span><span class="fu">sym</span>(TARGET)))</span>
<span id="cb96-23"><a href="modelo-para-detección-de-fraude.html#cb96-23" tabindex="-1"></a></span>
<span id="cb96-24"><a href="modelo-para-detección-de-fraude.html#cb96-24" tabindex="-1"></a>X <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">all_of</span>(FEATURES_ALL))</span>
<span id="cb96-25"><a href="modelo-para-detección-de-fraude.html#cb96-25" tabindex="-1"></a>y <span class="ot">&lt;-</span> datos[[TARGET]]</span></code></pre></div>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="modelo-para-detección-de-fraude.html#cb97-1" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 9
##   frecuencia pais_origen pais_destino tipo_trx tipo_psp unidad tipo_monto
##   &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt;        &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;     
## 1 A          AT          BG           TOTL     1        PN     A         
## 2 A          AT          BG           TOTL     1        PN     A         
## 3 A          AT          BG           TOTL     1        PN     A         
## 4 A          AT          BG           TOTL     1        PN     A         
## 5 A          AT          BG           TOTL     1        PN     A         
## 6 A          AT          BG           TOTL     1        PN     A         
## # ℹ 2 more variables: monto_final &lt;dbl&gt;, tipo_fraude_bin &lt;int&gt;</code></pre>
</div>
<div id="pre-procesamiento-con-columntransformer" class="section level3 hasAnchor" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Pre-procesamiento con ColumnTransformer<a href="modelo-para-detección-de-fraude.html#pre-procesamiento-con-columntransformer" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En Python se construyó un <code>ColumnTransformer</code> dentro de un <code>Pipeline</code> de <code>scikit-learn</code>
para garantizar que no haya fuga de datos entre entrenamiento y prueba. En el pipeline de las variables númericas se usa StandarScaler() y SimpleImputer con la mediana por si hay valores faltantes, para el pipeline de las categóricas se utiliza SimpleImputer con la moda por si hay valores NaN y OneHotEncoding para evitar multicolinealidad, además como no hay tantas categorías, no genera una alta cardinalidad.</p>
<table>
<colgroup>
<col width="23%" />
<col width="76%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Transformación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Numérica</td>
<td><code>SimpleImputer(mediana)</code> → <code>StandardScaler</code></td>
</tr>
<tr class="even">
<td>Categórica</td>
<td><code>SimpleImputer(moda)</code> → <code>OneHotEncoder(drop='first')</code></td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Variables numéricas:</strong> <code>monto_final</code> — imputación por mediana y estandarización.</li>
<li><strong>Variables categóricas:</strong>
imputación por moda y codificación One-Hot eliminando la primera categoría para
evitar multicolinealidad. Al no haber alta cardinalidad, este encoding no genera
un número excesivo de columnas.</li>
</ul>
<pre><code>## Preprocesador definido (ColumnTransformer)</code></pre>
<pre><code>## Numérico:   Imputer(mediana) → StandardScaler</code></pre>
<pre><code>## Categórico: Imputer(moda)    → OneHotEncoder</code></pre>
</div>
<div id="split-de-los-datos" class="section level3 hasAnchor" number="4.1.4">
<h3><span class="header-section-number">4.1.4</span> Split de los datos<a href="modelo-para-detección-de-fraude.html#split-de-los-datos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Antes de utilizar el modelo se debe hacer correctamente la división del grupo de
entrenamiento y el grupo de prueba. Debido a las clases desbalanceadas se utilizó
split estratificado, garantizando que cada partición mantiene la proporción original
de clases; de lo contrario, las particiones podrían no contener representación de
clases minoritarias.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="modelo-para-detección-de-fraude.html#cb102-1" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb102-2"><a href="modelo-para-detección-de-fraude.html#cb102-2" tabindex="-1"></a></span>
<span id="cb102-3"><a href="modelo-para-detección-de-fraude.html#cb102-3" tabindex="-1"></a><span class="co"># Equivalente a: train_test_split(..., test_size=0.20, stratify=y)</span></span>
<span id="cb102-4"><a href="modelo-para-detección-de-fraude.html#cb102-4" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb102-5"><a href="modelo-para-detección-de-fraude.html#cb102-5" tabindex="-1"></a></span>
<span id="cb102-6"><a href="modelo-para-detección-de-fraude.html#cb102-6" tabindex="-1"></a>indice_train <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(df<span class="sc">$</span>tipo_fraude, <span class="at">p =</span> <span class="fl">0.80</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb102-7"><a href="modelo-para-detección-de-fraude.html#cb102-7" tabindex="-1"></a></span>
<span id="cb102-8"><a href="modelo-para-detección-de-fraude.html#cb102-8" tabindex="-1"></a>train <span class="ot">&lt;-</span> df[ indice_train, ]</span>
<span id="cb102-9"><a href="modelo-para-detección-de-fraude.html#cb102-9" tabindex="-1"></a>test  <span class="ot">&lt;-</span> df[<span class="sc">-</span>indice_train, ]</span>
<span id="cb102-10"><a href="modelo-para-detección-de-fraude.html#cb102-10" tabindex="-1"></a></span>
<span id="cb102-11"><a href="modelo-para-detección-de-fraude.html#cb102-11" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Split estratificado: 80% Entrenamiento (Train) y 20% Prueba (Test)</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Split estratificado: 80% Entrenamiento (Train) y 20% Prueba (Test)</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="modelo-para-detección-de-fraude.html#cb104-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">&quot;Train: %d | Test: %d</span><span class="sc">\n</span><span class="st">&quot;</span>, <span class="fu">nrow</span>(train), <span class="fu">nrow</span>(test)))</span></code></pre></div>
<pre><code>## Train: 526356 | Test: 131587</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="modelo-para-detección-de-fraude.html#cb106-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st">Distribución en train:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Distribución en train:</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="modelo-para-detección-de-fraude.html#cb108-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(train<span class="sc">$</span>tipo_fraude)), <span class="dv">3</span>))</span></code></pre></div>
<pre><code>## 
## con fraude sin fraude 
##      0.003      0.997</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="modelo-para-detección-de-fraude.html#cb110-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st">Distribución en test:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Distribución en test:</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="modelo-para-detección-de-fraude.html#cb112-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(test<span class="sc">$</span>tipo_fraude)), <span class="dv">3</span>))</span></code></pre></div>
<pre><code>## 
## con fraude sin fraude 
##      0.003      0.997</code></pre>
</div>
<div id="validación-cruzada" class="section level3 hasAnchor" number="4.1.5">
<h3><span class="header-section-number">4.1.5</span> Validación cruzada<a href="modelo-para-detección-de-fraude.html#validaci%C3%B3n-cruzada" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Antes de continuar, para evitar la fuga de datos, es de vital importancia saber que no se debe mezclar la información del conjunto de prueba con el de entrenamiento, por tanto el fit() debe ser aplicado únicamente en el conjunto de entrenamiento. La solución a esto es usar pipelines: el fit() del pipeline llama al fit_transform() de cada paso sólo sobre training data, y el transform() final usa los parámetros aprendidos. Por último, se debe realizar la validación cruzada, se utilizará el método StratifiedKFold debido a que en este caso se tiene clases desbalanceadas, y se define la métrica de optimización. Dado el marcado desbalance de clases presente en el dataset, se optó por el F1-Score como métrica de optimización durante la búsqueda de hiperparámetros. Esta métrica representa la media armónica entre precisión y recall, penalizando los modelos que sacrifican una en favor de la otra. Si bien el PR-AUC se emplea como métrica de evaluación final por su sensibilidad a la clase positiva, el F1-Score resultó más efectivo para guiar la búsqueda de hiperparámetros.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="modelo-para-detección-de-fraude.html#cb114-1" tabindex="-1"></a>SCORING  <span class="ot">&lt;-</span> <span class="st">&quot;average_precision (PR-AUC)&quot;</span></span>
<span id="cb114-2"><a href="modelo-para-detección-de-fraude.html#cb114-2" tabindex="-1"></a>K_FOLDS  <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb114-3"><a href="modelo-para-detección-de-fraude.html#cb114-3" tabindex="-1"></a>SEED     <span class="ot">&lt;-</span> <span class="dv">42</span></span>
<span id="cb114-4"><a href="modelo-para-detección-de-fraude.html#cb114-4" tabindex="-1"></a></span>
<span id="cb114-5"><a href="modelo-para-detección-de-fraude.html#cb114-5" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">&quot;Validación: StratifiedKFold (k=%d, shuffle=TRUE, seed=%d)</span><span class="sc">\n</span><span class="st">&quot;</span>, K_FOLDS, SEED))</span></code></pre></div>
<pre><code>## Validación: StratifiedKFold (k=5, shuffle=TRUE, seed=42)</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="modelo-para-detección-de-fraude.html#cb116-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">&quot;Métrica de optimización: %s</span><span class="sc">\n</span><span class="st">&quot;</span>, SCORING))</span></code></pre></div>
<pre><code>## Métrica de optimización: average_precision (PR-AUC)</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="modelo-para-detección-de-fraude.html#cb118-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st">Métricas evaluadas:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Métricas evaluadas:</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="modelo-para-detección-de-fraude.html#cb120-1" tabindex="-1"></a>metricas <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb120-2"><a href="modelo-para-detección-de-fraude.html#cb120-2" tabindex="-1"></a>  <span class="at">Clave     =</span> <span class="fu">c</span>(<span class="st">&quot;pr_auc&quot;</span>, <span class="st">&quot;roc_auc&quot;</span>, <span class="st">&quot;f1&quot;</span>, <span class="st">&quot;recall&quot;</span>, <span class="st">&quot;precision&quot;</span>, <span class="st">&quot;balanced_accuracy&quot;</span>),</span>
<span id="cb120-3"><a href="modelo-para-detección-de-fraude.html#cb120-3" tabindex="-1"></a>  Métrica   <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;PR-AUC&quot;</span>, <span class="st">&quot;ROC-AUC&quot;</span>, <span class="st">&quot;F1-Score&quot;</span>, <span class="st">&quot;Recall&quot;</span>, <span class="st">&quot;Precision&quot;</span>, <span class="st">&quot;Balanced Accuracy&quot;</span>)</span>
<span id="cb120-4"><a href="modelo-para-detección-de-fraude.html#cb120-4" tabindex="-1"></a>)</span>
<span id="cb120-5"><a href="modelo-para-detección-de-fraude.html#cb120-5" tabindex="-1"></a><span class="fu">print</span>(metricas, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>##              Clave           Métrica
##             pr_auc            PR-AUC
##            roc_auc           ROC-AUC
##                 f1          F1-Score
##             recall            Recall
##          precision         Precision
##  balanced_accuracy Balanced Accuracy</code></pre>
</div>
<div id="pipeline-para-el-entrenamiento-de-modelos" class="section level3 hasAnchor" number="4.1.6">
<h3><span class="header-section-number">4.1.6</span> Pipeline para el entrenamiento de modelos<a href="modelo-para-detección-de-fraude.html#pipeline-para-el-entrenamiento-de-modelos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se evaluaron los siguientes modelos de Machine Learning:</p>
<ul>
<li><strong>Regresión Logística:</strong> modelo base, solver <code>saga</code>, penalización L1/L2.</li>
<li><strong>Naive Bayes:</strong> implementado con <code>partial_fit</code> por chunks para evitar problemas de memoria.</li>
<li><strong>LinearSVC:</strong> versión rápida de SVM, con <code>CalibratedClassifierCV</code> para obtener probabilidades.</li>
<li><strong>XGBoost:</strong> con <code>tree_method='hist'</code> y aceleración GPU (<code>device='cuda'</code>).</li>
<li><strong>Random Forest:</strong> implementación completa con búsqueda de hiperparámetros.</li>
</ul>
<p>Para la optimización de hiperparámetros se utilizó <code>RandomizedSearchCV</code> (20 iteraciones),
que ofrece mejor relación tiempo/rendimiento frente a <code>GridSearchCV</code>.</p>
<p>Para tratar el <strong>desbalanceo de clases</strong> se evaluaron cuatro estrategias por cada modelo:</p>
<table>
<colgroup>
<col width="22%" />
<col width="77%" />
</colgroup>
<thead>
<tr class="header">
<th>Estrategia</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>sin_balanceo</code></td>
<td>Dataset original sin modificación</td>
</tr>
<tr class="even">
<td><code>smote</code></td>
<td>Sobremuestreo sintético de la clase minoritaria</td>
</tr>
<tr class="odd">
<td><code>adasyn</code></td>
<td>Sobremuestreo adaptativo según densidad local</td>
</tr>
<tr class="even">
<td><code>weights</code></td>
<td><code>class_weight='balanced'</code> o <code>scale_pos_weight</code> en XGBoost</td>
</tr>
</tbody>
</table>
<pre><code>##               Modelo                     Estrategia_balanceo
##              XGBoost sin_balanceo | smote | adasyn | weights
##  Logistic Regression sin_balanceo | smote | adasyn | weights
##          Naive Bayes sin_balanceo | smote | adasyn | weights
##            LinearSVC sin_balanceo | smote | adasyn | weights
##        Random Forest sin_balanceo | smote | adasyn | weights
##                                            Optimizacion
##  RandomizedSearchCV (n_iter=20, CV=StratifiedKFold k=5)
##  RandomizedSearchCV (n_iter=20, CV=StratifiedKFold k=5)
##  RandomizedSearchCV (n_iter=20, CV=StratifiedKFold k=5)
##  RandomizedSearchCV (n_iter=20, CV=StratifiedKFold k=5)
##  RandomizedSearchCV (n_iter=20, CV=StratifiedKFold k=5)</code></pre>
<pre><code>## 
## Estrategias de balanceo evaluadas:</code></pre>
<pre><code>##        Nombre                                    Tecnica
##  sin_balanceo                           Sin modificación
##         smote            SMOTE (sobremuestreo sintético)
##        adasyn          ADASYN (sobremuestreo adaptativo)
##       weights class_weight=&#39;balanced&#39; / scale_pos_weight</code></pre>
</div>
<div id="estructura-del-pipeline" class="section level3 hasAnchor" number="4.1.7">
<h3><span class="header-section-number">4.1.7</span> Estructura del Pipeline<a href="modelo-para-detección-de-fraude.html#estructura-del-pipeline" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cada modelo sigue la misma estructura de pipeline para garantizar la no fuga de datos:</p>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-72">Table 4.1: </span><span id="tab:unnamed-chunk-72">Table 4.2: </span>Estructura del Pipeline
</caption>
<thead>
<tr>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
Paso
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
Componente
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
Descripción
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
<ol style="list-style-type: decimal">
<li>preprocessor
</td>
<td style="text-align:center;">
ColumnTransformer
</td>
<td style="text-align:center;">
Scaling + One-Hot Encoding
</td>
</tr>
<tr>
<td style="text-align:center;">
<ol start="2" style="list-style-type: decimal">
<li>balancer
</td>
<td style="text-align:center;">
SMOTE / ADASYN
</td>
<td style="text-align:center;">
Solo si aplica
</td>
</tr>
<tr>
<td style="text-align:center;">
<ol start="3" style="list-style-type: decimal">
<li>classifier
</td>
<td style="text-align:center;">
&lt;Modelo&gt;
</td>
<td style="text-align:center;">
Modelo final
</td>
</tr>
</tbody>
</table></li>
</ol></li>
</ol></li>
</ol>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-72">Table 4.1: </span>Hiperparámetros por modelo — RandomizedSearchCV (n_iter=20)
</caption>
<thead>
<tr>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
Modelo
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
Hiperparámetro
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
Distribución
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;vertical-align: middle !important;" rowspan="5">
XGBoost
</td>
<td style="text-align:center;">
n_estimators
</td>
<td style="text-align:center;">
Uniform(50, 200)
</td>
</tr>
<tr>
<td style="text-align:center;">
max_depth
</td>
<td style="text-align:center;">
Uniform(3, 6)
</td>
</tr>
<tr>
<td style="text-align:center;">
learning_rate
</td>
<td style="text-align:center;">
LogUniform(0.05, 0.15)
</td>
</tr>
<tr>
<td style="text-align:center;">
subsample
</td>
<td style="text-align:center;">
Uniform(0.7, 0.9)
</td>
</tr>
<tr>
<td style="text-align:center;">
scale_pos_weight
</td>
<td style="text-align:center;">
Uniform(4, scale_weight×1.5) — solo weights
</td>
</tr>
<tr>
<td style="text-align:center;vertical-align: middle !important;" rowspan="3">
Logistic Regression
</td>
<td style="text-align:center;">
C
</td>
<td style="text-align:center;">
LogUniform(1e-3, 10)
</td>
</tr>
<tr>
<td style="text-align:center;">
penalty
</td>
<td style="text-align:center;">
[‘l1’, ‘l2’]
</td>
</tr>
<tr>
<td style="text-align:center;">
max_iter
</td>
<td style="text-align:center;">
Uniform(500, 2000)
</td>
</tr>
<tr>
<td style="text-align:center;vertical-align: middle !important;" rowspan="2">
Naive Bayes
</td>
<td style="text-align:center;">
var_smoothing
</td>
<td style="text-align:center;">
LogUniform(1e-12, 1e-6)
</td>
</tr>
<tr>
<td style="text-align:center;">
chunk_size
</td>
<td style="text-align:center;">
[5000, 10000, 20000]
</td>
</tr>
<tr>
<td style="text-align:center;vertical-align: middle !important;" rowspan="2">
LinearSVC
</td>
<td style="text-align:center;">
C
</td>
<td style="text-align:center;">
LogUniform(1e-3, 10)
</td>
</tr>
<tr>
<td style="text-align:center;">
max_iter
</td>
<td style="text-align:center;">
Uniform(1000, 5000)
</td>
</tr>
<tr>
<td style="text-align:center;vertical-align: middle !important;" rowspan="5">
Random Forest
</td>
<td style="text-align:center;">
n_estimators
</td>
<td style="text-align:center;">
Uniform(50, 300)
</td>
</tr>
<tr>
<td style="text-align:center;">
max_depth
</td>
<td style="text-align:center;">
[None, 5, 10, 20]
</td>
</tr>
<tr>
<td style="text-align:center;">
min_samples_split
</td>
<td style="text-align:center;">
Uniform(2, 20)
</td>
</tr>
<tr>
<td style="text-align:center;">
min_samples_leaf
</td>
<td style="text-align:center;">
Uniform(1, 10)
</td>
</tr>
<tr>
<td style="text-align:center;">
max_features
</td>
<td style="text-align:center;">
[‘sqrt’, ‘log2’]
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="resultados" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Resultados<a href="modelo-para-detección-de-fraude.html#resultados" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A continuación se presenta una tabla comparativa con todos los modelos entrenados: XGBoost, Logistic Regression (Ridge/Lasso), Naive Bayes, LinearSVC y Random Forest. A cada uno se le aplicaron técnicas de balanceo (SMOTE, ADASYN y Weights) dado el marcado desbalance de la clase objetivo (con fraude), y también se evaluó cada algoritmo sin balanceo. Para cada combinación se registraron las métricas de rendimiento y el tiempo de entrenamiento, dando como resultado 20 configuraciones evaluadas en total.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="modelo-para-detección-de-fraude.html#cb125-1" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb125-2"><a href="modelo-para-detección-de-fraude.html#cb125-2" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb125-3"><a href="modelo-para-detección-de-fraude.html#cb125-3" tabindex="-1"></a></span>
<span id="cb125-4"><a href="modelo-para-detección-de-fraude.html#cb125-4" tabindex="-1"></a>archivo_modelos <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;comparacion_modelos.csv&quot;</span>)</span>
<span id="cb125-5"><a href="modelo-para-detección-de-fraude.html#cb125-5" tabindex="-1"></a></span>
<span id="cb125-6"><a href="modelo-para-detección-de-fraude.html#cb125-6" tabindex="-1"></a></span>
<span id="cb125-7"><a href="modelo-para-detección-de-fraude.html#cb125-7" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(archivo_modelos, <span class="dv">20</span>), <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">align =</span> <span class="st">&quot;c&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb125-8"><a href="modelo-para-detección-de-fraude.html#cb125-8" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>, <span class="st">&quot;condensed&quot;</span>),</span>
<span id="cb125-9"><a href="modelo-para-detección-de-fraude.html#cb125-9" tabindex="-1"></a>                <span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
modelo
</th>
<th style="text-align:center;">
balanceo
</th>
<th style="text-align:center;">
f1_cv_refit
</th>
<th style="text-align:center;">
pr_auc_cv
</th>
<th style="text-align:center;">
roc_auc_cv
</th>
<th style="text-align:center;">
recall_cv
</th>
<th style="text-align:center;">
precision_cv
</th>
<th style="text-align:center;">
f1_cv
</th>
<th style="text-align:center;">
pr_auc_test
</th>
<th style="text-align:center;">
roc_auc_test
</th>
<th style="text-align:center;">
tiempo_s
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Random_Forest
</td>
<td style="text-align:center;">
sin_balanceo
</td>
<td style="text-align:center;">
0.8886
</td>
<td style="text-align:center;">
0.9734
</td>
<td style="text-align:center;">
0.9999
</td>
<td style="text-align:center;">
0.8380
</td>
<td style="text-align:center;">
0.9465
</td>
<td style="text-align:center;">
0.8886
</td>
<td style="text-align:center;">
0.9659
</td>
<td style="text-align:center;">
0.9998
</td>
<td style="text-align:center;">
1361.9
</td>
</tr>
<tr>
<td style="text-align:center;">
XGBoost_hist
</td>
<td style="text-align:center;">
sin_balanceo
</td>
<td style="text-align:center;">
0.8577
</td>
<td style="text-align:center;">
0.9573
</td>
<td style="text-align:center;">
0.9998
</td>
<td style="text-align:center;">
0.7923
</td>
<td style="text-align:center;">
0.9357
</td>
<td style="text-align:center;">
0.8577
</td>
<td style="text-align:center;">
0.9522
</td>
<td style="text-align:center;">
0.9998
</td>
<td style="text-align:center;">
115.8
</td>
</tr>
<tr>
<td style="text-align:center;">
Random_Forest
</td>
<td style="text-align:center;">
weights
</td>
<td style="text-align:center;">
0.9009
</td>
<td style="text-align:center;">
0.9461
</td>
<td style="text-align:center;">
0.9999
</td>
<td style="text-align:center;">
0.9814
</td>
<td style="text-align:center;">
0.8328
</td>
<td style="text-align:center;">
0.9009
</td>
<td style="text-align:center;">
0.9404
</td>
<td style="text-align:center;">
0.9998
</td>
<td style="text-align:center;">
1457.5
</td>
</tr>
<tr>
<td style="text-align:center;">
Random_Forest
</td>
<td style="text-align:center;">
smote
</td>
<td style="text-align:center;">
0.9115
</td>
<td style="text-align:center;">
0.9427
</td>
<td style="text-align:center;">
0.9986
</td>
<td style="text-align:center;">
0.9280
</td>
<td style="text-align:center;">
0.8961
</td>
<td style="text-align:center;">
0.9115
</td>
<td style="text-align:center;">
0.9297
</td>
<td style="text-align:center;">
0.9985
</td>
<td style="text-align:center;">
4152.5
</td>
</tr>
<tr>
<td style="text-align:center;">
Random_Forest
</td>
<td style="text-align:center;">
adasyn
</td>
<td style="text-align:center;">
0.9106
</td>
<td style="text-align:center;">
0.9361
</td>
<td style="text-align:center;">
0.9995
</td>
<td style="text-align:center;">
0.9273
</td>
<td style="text-align:center;">
0.8950
</td>
<td style="text-align:center;">
0.9106
</td>
<td style="text-align:center;">
0.9226
</td>
<td style="text-align:center;">
0.9998
</td>
<td style="text-align:center;">
3905.1
</td>
</tr>
<tr>
<td style="text-align:center;">
XGBoost_hist
</td>
<td style="text-align:center;">
adasyn
</td>
<td style="text-align:center;">
0.6319
</td>
<td style="text-align:center;">
0.9231
</td>
<td style="text-align:center;">
0.9997
</td>
<td style="text-align:center;">
0.9910
</td>
<td style="text-align:center;">
0.4639
</td>
<td style="text-align:center;">
0.6319
</td>
<td style="text-align:center;">
0.9166
</td>
<td style="text-align:center;">
0.9997
</td>
<td style="text-align:center;">
290.1
</td>
</tr>
<tr>
<td style="text-align:center;">
XGBoost_hist
</td>
<td style="text-align:center;">
weights
</td>
<td style="text-align:center;">
0.5140
</td>
<td style="text-align:center;">
0.9065
</td>
<td style="text-align:center;">
0.9997
</td>
<td style="text-align:center;">
0.9981
</td>
<td style="text-align:center;">
0.3461
</td>
<td style="text-align:center;">
0.5140
</td>
<td style="text-align:center;">
0.9062
</td>
<td style="text-align:center;">
0.9997
</td>
<td style="text-align:center;">
98.7
</td>
</tr>
<tr>
<td style="text-align:center;">
XGBoost_hist
</td>
<td style="text-align:center;">
smote
</td>
<td style="text-align:center;">
0.6373
</td>
<td style="text-align:center;">
0.9300
</td>
<td style="text-align:center;">
0.9998
</td>
<td style="text-align:center;">
0.9942
</td>
<td style="text-align:center;">
0.4692
</td>
<td style="text-align:center;">
0.6373
</td>
<td style="text-align:center;">
0.9038
</td>
<td style="text-align:center;">
0.9997
</td>
<td style="text-align:center;">
246.4
</td>
</tr>
<tr>
<td style="text-align:center;">
LinearSVC
</td>
<td style="text-align:center;">
sin_balanceo
</td>
<td style="text-align:center;">
0.7066
</td>
<td style="text-align:center;">
0.7037
</td>
<td style="text-align:center;">
0.9981
</td>
<td style="text-align:center;">
0.6733
</td>
<td style="text-align:center;">
0.7444
</td>
<td style="text-align:center;">
0.7066
</td>
<td style="text-align:center;">
0.6844
</td>
<td style="text-align:center;">
0.9977
</td>
<td style="text-align:center;">
113.4
</td>
</tr>
<tr>
<td style="text-align:center;">
Logistic_Regression
</td>
<td style="text-align:center;">
sin_balanceo
</td>
<td style="text-align:center;">
0.7126
</td>
<td style="text-align:center;">
0.7073
</td>
<td style="text-align:center;">
0.9990
</td>
<td style="text-align:center;">
0.6900
</td>
<td style="text-align:center;">
0.7381
</td>
<td style="text-align:center;">
0.7126
</td>
<td style="text-align:center;">
0.6792
</td>
<td style="text-align:center;">
0.9989
</td>
<td style="text-align:center;">
937.4
</td>
</tr>
<tr>
<td style="text-align:center;">
LinearSVC
</td>
<td style="text-align:center;">
weights
</td>
<td style="text-align:center;">
0.4925
</td>
<td style="text-align:center;">
0.6088
</td>
<td style="text-align:center;">
0.9989
</td>
<td style="text-align:center;">
0.4019
</td>
<td style="text-align:center;">
0.6396
</td>
<td style="text-align:center;">
0.4925
</td>
<td style="text-align:center;">
0.5836
</td>
<td style="text-align:center;">
0.9989
</td>
<td style="text-align:center;">
141.0
</td>
</tr>
<tr>
<td style="text-align:center;">
Logistic_Regression
</td>
<td style="text-align:center;">
smote
</td>
<td style="text-align:center;">
0.5550
</td>
<td style="text-align:center;">
0.5693
</td>
<td style="text-align:center;">
0.9989
</td>
<td style="text-align:center;">
0.9987
</td>
<td style="text-align:center;">
0.3843
</td>
<td style="text-align:center;">
0.5550
</td>
<td style="text-align:center;">
0.5500
</td>
<td style="text-align:center;">
0.9988
</td>
<td style="text-align:center;">
2275.5
</td>
</tr>
<tr>
<td style="text-align:center;">
Logistic_Regression
</td>
<td style="text-align:center;">
adasyn
</td>
<td style="text-align:center;">
0.5579
</td>
<td style="text-align:center;">
0.5405
</td>
<td style="text-align:center;">
0.9987
</td>
<td style="text-align:center;">
0.9987
</td>
<td style="text-align:center;">
0.3872
</td>
<td style="text-align:center;">
0.5579
</td>
<td style="text-align:center;">
0.5224
</td>
<td style="text-align:center;">
0.9987
</td>
<td style="text-align:center;">
2488.0
</td>
</tr>
<tr>
<td style="text-align:center;">
LinearSVC
</td>
<td style="text-align:center;">
smote
</td>
<td style="text-align:center;">
0.5618
</td>
<td style="text-align:center;">
0.5364
</td>
<td style="text-align:center;">
0.9987
</td>
<td style="text-align:center;">
0.9987
</td>
<td style="text-align:center;">
0.3909
</td>
<td style="text-align:center;">
0.5618
</td>
<td style="text-align:center;">
0.5223
</td>
<td style="text-align:center;">
0.9987
</td>
<td style="text-align:center;">
589.6
</td>
</tr>
<tr>
<td style="text-align:center;">
LinearSVC
</td>
<td style="text-align:center;">
adasyn
</td>
<td style="text-align:center;">
0.5140
</td>
<td style="text-align:center;">
0.5188
</td>
<td style="text-align:center;">
0.9986
</td>
<td style="text-align:center;">
0.9994
</td>
<td style="text-align:center;">
0.3462
</td>
<td style="text-align:center;">
0.5140
</td>
<td style="text-align:center;">
0.5113
</td>
<td style="text-align:center;">
0.9987
</td>
<td style="text-align:center;">
513.7
</td>
</tr>
<tr>
<td style="text-align:center;">
Logistic_Regression
</td>
<td style="text-align:center;">
weights
</td>
<td style="text-align:center;">
0.5400
</td>
<td style="text-align:center;">
0.4812
</td>
<td style="text-align:center;">
0.9983
</td>
<td style="text-align:center;">
0.9994
</td>
<td style="text-align:center;">
0.3727
</td>
<td style="text-align:center;">
0.5400
</td>
<td style="text-align:center;">
0.4473
</td>
<td style="text-align:center;">
0.9982
</td>
<td style="text-align:center;">
14739.3
</td>
</tr>
<tr>
<td style="text-align:center;">
Naive_Bayes
</td>
<td style="text-align:center;">
smote
</td>
<td style="text-align:center;">
0.3152
</td>
<td style="text-align:center;">
0.1870
</td>
<td style="text-align:center;">
0.9932
</td>
<td style="text-align:center;">
0.9987
</td>
<td style="text-align:center;">
0.1871
</td>
<td style="text-align:center;">
0.3152
</td>
<td style="text-align:center;">
0.1871
</td>
<td style="text-align:center;">
0.9936
</td>
<td style="text-align:center;">
161.0
</td>
</tr>
<tr>
<td style="text-align:center;">
Naive_Bayes
</td>
<td style="text-align:center;">
weights
</td>
<td style="text-align:center;">
0.3130
</td>
<td style="text-align:center;">
0.1864
</td>
<td style="text-align:center;">
0.9935
</td>
<td style="text-align:center;">
1.0000
</td>
<td style="text-align:center;">
0.1856
</td>
<td style="text-align:center;">
0.3130
</td>
<td style="text-align:center;">
0.1864
</td>
<td style="text-align:center;">
0.9935
</td>
<td style="text-align:center;">
69.6
</td>
</tr>
<tr>
<td style="text-align:center;">
Naive_Bayes
</td>
<td style="text-align:center;">
sin_balanceo
</td>
<td style="text-align:center;">
0.3130
</td>
<td style="text-align:center;">
0.1864
</td>
<td style="text-align:center;">
0.9935
</td>
<td style="text-align:center;">
1.0000
</td>
<td style="text-align:center;">
0.1856
</td>
<td style="text-align:center;">
0.3130
</td>
<td style="text-align:center;">
0.1864
</td>
<td style="text-align:center;">
0.9935
</td>
<td style="text-align:center;">
70.9
</td>
</tr>
<tr>
<td style="text-align:center;">
Naive_Bayes
</td>
<td style="text-align:center;">
adasyn
</td>
<td style="text-align:center;">
0.2998
</td>
<td style="text-align:center;">
0.1765
</td>
<td style="text-align:center;">
0.9931
</td>
<td style="text-align:center;">
1.0000
</td>
<td style="text-align:center;">
0.1764
</td>
<td style="text-align:center;">
0.2998
</td>
<td style="text-align:center;">
0.1742
</td>
<td style="text-align:center;">
0.9930
</td>
<td style="text-align:center;">
203.8
</td>
</tr>
</tbody>
</table>
<p>La elección de los modelos responde a una estrategia de modelado basada en un espectro deliberado de complejidad, que permite contrastar diversos supuestos estadísticos. Se incluyeron modelos lineales y probabilísticos (Logistic Regression, LinearSVC y Naive Bayes) para establecer una línea base de rendimiento e interpretabilidad, evaluando si el problema puede resolverse con fronteras de decisión simples. Estos modelos actúan como punto de control para determinar si la complejidad adicional de algoritmos más pesados está justificada por una mejora significativa en las métricas.</p>
<p>Complementariamente, se integraron ensambles no lineales (Random Forest y XGBoost) para capturar interacciones complejas y patrones no paramétricos en los datos. Random Forest aporta robustez frente al ruido mediante bagging, mientras que XGBoost representa el estado del arte en datos tabulares, optimizando secuencialmente los errores y manejando el desbalance de clases de forma nativa. Esta comparativa entre modelos simples y ensambles garantiza una justificación técnica sólida antes de comprometerse con el modelo final para producción.</p>
<div id="mejores-parámetros-de-cada-modelo" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Mejores parámetros de cada modelo<a href="modelo-para-detección-de-fraude.html#mejores-par%C3%A1metros-de-cada-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>XGBoost</li>
</ul>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-73">Table 4.3: </span>Mejores Hiperparámetros — XGBoost
</caption>
<thead>
<tr>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
balanceo
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
learning_rate
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
max_depth
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
n_estimators
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
subsample
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
scale_pos_weight
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
adasyn
</td>
<td style="text-align:center;">
0.0965168
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
171
</td>
<td style="text-align:center;">
0.8403951
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
sin_balanceo
</td>
<td style="text-align:center;">
0.0965168
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
171
</td>
<td style="text-align:center;">
0.8403951
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
smote
</td>
<td style="text-align:center;">
0.0965168
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
171
</td>
<td style="text-align:center;">
0.8403951
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
weights
</td>
<td style="text-align:center;">
0.0904625
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
173
</td>
<td style="text-align:center;">
0.9666462
</td>
<td style="text-align:center;">
142.617
</td>
</tr>
</tbody>
</table>
<ul>
<li>Random Forest</li>
</ul>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-74">Table 4.4: </span>Mejores Hiperparámetros — Random Forest
</caption>
<thead>
<tr>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
balanceo
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
n_estimators
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
max_features
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
min_samples_leaf
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
min_samples_split
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
adasyn
</td>
<td style="text-align:center;">
58
</td>
<td style="text-align:center;">
sqrt
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
8
</td>
</tr>
<tr>
<td style="text-align:center;">
sin_balanceo
</td>
<td style="text-align:center;">
58
</td>
<td style="text-align:center;">
sqrt
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
8
</td>
</tr>
<tr>
<td style="text-align:center;">
smote
</td>
<td style="text-align:center;">
58
</td>
<td style="text-align:center;">
sqrt
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
8
</td>
</tr>
<tr>
<td style="text-align:center;">
weights
</td>
<td style="text-align:center;">
58
</td>
<td style="text-align:center;">
sqrt
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
8
</td>
</tr>
</tbody>
</table>
<ul>
<li>Logistic Regression</li>
</ul>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-75">Table 4.5: </span>Mejores Hiperparámetros — Logistic Regression
</caption>
<thead>
<tr>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
balanceo
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
C
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
max_iter
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
penalty
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
adasyn
</td>
<td style="text-align:center;">
0.8471801
</td>
<td style="text-align:center;">
1544
</td>
<td style="text-align:center;">
l1
</td>
</tr>
<tr>
<td style="text-align:center;">
sin_balanceo
</td>
<td style="text-align:center;">
5.6782020
</td>
<td style="text-align:center;">
885
</td>
<td style="text-align:center;">
l2
</td>
</tr>
<tr>
<td style="text-align:center;">
smote
</td>
<td style="text-align:center;">
0.8471801
</td>
<td style="text-align:center;">
1544
</td>
<td style="text-align:center;">
l1
</td>
</tr>
<tr>
<td style="text-align:center;">
weights
</td>
<td style="text-align:center;">
0.8471801
</td>
<td style="text-align:center;">
1544
</td>
<td style="text-align:center;">
l1
</td>
</tr>
</tbody>
</table>
<ul>
<li>LinearSVC</li>
</ul>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-76">Table 4.6: </span>Mejores Hiperparámetros — LinearSVC
</caption>
<thead>
<tr>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
balanceo
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
C
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
max_iter
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
adasyn
</td>
<td style="text-align:center;">
0.1140086
</td>
<td style="text-align:center;">
3879
</td>
</tr>
<tr>
<td style="text-align:center;">
sin_balanceo
</td>
<td style="text-align:center;">
0.2481041
</td>
<td style="text-align:center;">
2638
</td>
</tr>
<tr>
<td style="text-align:center;">
smote
</td>
<td style="text-align:center;">
2.1368329
</td>
<td style="text-align:center;">
3853
</td>
</tr>
<tr>
<td style="text-align:center;">
weights
</td>
<td style="text-align:center;">
0.0010072
</td>
<td style="text-align:center;">
1955
</td>
</tr>
</tbody>
</table>
<ul>
<li>Naive Bayes</li>
</ul>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-77">Table 4.7: </span>Mejores Hiperparámetros — Naive Bayes
</caption>
<thead>
<tr>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
balanceo
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
chunk_size
</th>
<th style="text-align:center;font-weight: bold;color: white !important;background-color: rgba(44, 62, 80, 255) !important;">
var_smoothing
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
adasyn
</td>
<td style="text-align:center;">
20000
</td>
<td style="text-align:center;">
8e-07
</td>
</tr>
<tr>
<td style="text-align:center;">
sin_balanceo
</td>
<td style="text-align:center;">
20000
</td>
<td style="text-align:center;">
8e-07
</td>
</tr>
<tr>
<td style="text-align:center;">
smote
</td>
<td style="text-align:center;">
20000
</td>
<td style="text-align:center;">
1e-07
</td>
</tr>
<tr>
<td style="text-align:center;">
weights
</td>
<td style="text-align:center;">
20000
</td>
<td style="text-align:center;">
8e-07
</td>
</tr>
</tbody>
</table>
</div>
<div id="comparación-de-las-técnicas-de-balanceo" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Comparación de las técnicas de balanceo<a href="modelo-para-detección-de-fraude.html#comparaci%C3%B3n-de-las-t%C3%A9cnicas-de-balanceo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Tras evaluar las 20 configuraciones resultantes de combinar los cinco modelos con las cuatro estrategias de balanceo, se seleccionan Random Forest y XGBoost como modelos finalistas para el análisis comparativo estadístico y de explicabilidad. Esta decisión se sustenta en que ambos fueron los únicos que superaron un PR-AUC test de 0.90, con valores de 0.9659 y 0.9522 respectivamente bajo la estrategia sin balanceo. En contraste, Logistic Regression (0.6792), LinearSVC (0.6844) y Naive Bayes (0.1864) quedaron muy por debajo del umbral de rendimiento aceptable para un problema de detección de fraude. Adicionalmente, Random Forest y XGBoost mantuvieron una precisión superior a 0.93 con un recall razonable, lo que confirma que aprendieron patrones reales de fraude sin requerir técnicas artificiales de balanceo para alcanzar su mejor rendimiento.</p>
<table>
<thead>
<tr class="header">
<th align="center">Modelo A</th>
<th align="center">Modelo B</th>
<th align="center">Dif AUC</th>
<th align="center">IC 95%</th>
<th align="center">p-valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Random Forest</td>
<td align="center">XGBoost</td>
<td align="center">0.000</td>
<td align="center">[-0.000, 0.000]</td>
<td align="center">0.922</td>
</tr>
<tr class="even">
<td align="center">Random Forest</td>
<td align="center">Naive Bayes</td>
<td align="center">0.007</td>
<td align="center">[0.006, 0.007]</td>
<td align="center">0.000</td>
</tr>
<tr class="odd">
<td align="center">Random Forest</td>
<td align="center">LinearSVC</td>
<td align="center">0.002</td>
<td align="center">[0.001, 0.004]</td>
<td align="center">0.000</td>
</tr>
<tr class="even">
<td align="center">XGBoost</td>
<td align="center">Naive Bayes</td>
<td align="center">0.007</td>
<td align="center">[0.006, 0.007]</td>
<td align="center">0.000</td>
</tr>
<tr class="odd">
<td align="center">XGBoost</td>
<td align="center">LinearSVC</td>
<td align="center">0.002</td>
<td align="center">[0.001, 0.004]</td>
<td align="center">0.000</td>
</tr>
</tbody>
</table>
<pre><code>## 
## Intervalos de confianza 95% Bootstrap — PR-AUC test:</code></pre>
<table>
<thead>
<tr class="header">
<th align="center">Modelo</th>
<th align="center">PR-AUC</th>
<th align="center">IC 95%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Random Forest</td>
<td align="center">0.9659</td>
<td align="center">[0.9537, 0.9761]</td>
</tr>
<tr class="even">
<td align="center">XGBoost</td>
<td align="center">0.9522</td>
<td align="center">[0.9357, 0.9656]</td>
</tr>
<tr class="odd">
<td align="center">Naive Bayes</td>
<td align="center">0.1753</td>
<td align="center">[0.1607, 0.1902]</td>
</tr>
<tr class="even">
<td align="center">LinearSVC</td>
<td align="center">0.6844</td>
<td align="center">[0.6319, 0.7411]</td>
</tr>
</tbody>
</table>
<p>El Bootstrap se utiliza porque permite estimar la distribución de una métrica sin asumir normalidad en los datos. En lugar de una fórmula cerrada, remuestrea el conjunto de test 1000 veces con reemplazo y recalcula la métrica en cada iteración, construyendo así un intervalo de confianza empírico al 95%. Esto es especialmente apropiado en detección de fraude, donde el desbalanceo extremo (0.3% positivos) hace que los supuestos paramétricos clásicos sean poco confiables, y donde pequeñas diferencias en métricas como PR-AUC o ROC-AUC pueden tener alto impacto operativo.</p>
<p>Adempás, En la comparación por ROC-AUC, Random Forest y XGBoost son estadísticamente indistinguibles (diferencia de -0.000, p=0.922), lo que confirma que ambos modelos separan las clases con igual efectividad en términos de ranking. Sin embargo, ambos superan significativamente a Naive Bayes y LinearSVC (p=0.000 en todos los casos), con diferencias pequeñas en magnitud pero con intervalos de confianza que no cruzan el cero, lo que las hace estadísticamente robustas.</p>
<p>La historia más reveladora la cuenta el PR-AUC Bootstrap, que penaliza directamente el rendimiento sobre la clase minoritaria. Random Forest (0.9659, IC=[0.9537, 0.9761]) supera a XGBoost (0.9522, IC=[0.9357, 0.9656]) con intervalos que apenas se solapan, sugiriendo una ventaja real aunque no dramática. Ambos dejan muy atrás a LinearSVC (0.6844) y especialmente a Naive Bayes (0.1753), cuyo PR-AUC cercano al azar evidencia que su alto recall se logra a costa de clasificar casi todo como fraude. Random Forest sin balanceo es el modelo final recomendado, con el mejor PR-AUC test y la estimación bootstrap más estable.</p>
</div>
<div id="interpretabilidad-con-lime" class="section level3 hasAnchor" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Interpretabilidad con LIME<a href="modelo-para-detección-de-fraude.html#interpretabilidad-con-lime" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="lime_Random_Forest.png" alt="" width="1342" style="display: block; margin: auto;" /><img src="lime_XGBoost.png" alt="" width="1342" style="display: block; margin: auto;" /></p>
<p>En los 6 casos analizados (3 por modelo), emerge un patrón claro y repetido: pais_destino_W0 &gt; 0.00 es la variable con mayor contribución positiva al score de fraude en todas las observaciones, alcanzando contribuciones de hasta +0.06 en XGBoost y +0.05 en Random Forest. Esto indica que las transacciones hacia este destino son el predictor más fuerte de fraude para ambos modelos. tipo_trx_CP0 &gt; 0.00 y la frecuencia_H (entre 0.00 y 1.00) también aparecen como señales de fraude consistentes. Por el contrario, variables como pais_origen_B0 &lt;= 0.00, pais_origen_U2 &lt;= 0.00 y diversos destinos (AU, TR, IN, JP, ID) aparecen en azul, actuando como factores que restan probabilidad de fraude.</p>
<p>Ambos modelos coinciden en las variables clave, aunque XGBoost muestra una concentración de peso ligeramente mayor en la variable principal, mientras que Random Forest llega a predecir una probabilidad de 1.000 en la observación 56215. Las probabilidades en todos los casos son extremadamente altas (superiores a 0.987), lo que refleja que ambos clasificadores identifican señales de fraude muy contundentes.</p>
</div>
<div id="conclusión" class="section level3 hasAnchor" number="4.2.4">
<h3><span class="header-section-number">4.2.4</span> Conclusión<a href="modelo-para-detección-de-fraude.html#conclusi%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Este trabajo desarrolló un sistema de detección de fraude en transacciones financieras sobre un dataset de 657,943 registros con un desbalanceo extremo del 0.3% de casos positivos. Se evaluaron cinco modelos de clasificación (Regresión Logística, Naive Bayes, LinearSVC, XGBoost y Random Forest) bajo cuatro estrategias de balanceo (sin balanceo, SMOTE, ADASYN y pesos por clase), utilizando el F1-Score como métrica de optimización durante la búsqueda de hiperparámetros y el PR-AUC como métrica principal de evaluación, por su sensibilidad ante clases desbalanceadas.</p>
<p>El hallazgo más relevante del proceso de modelado fue que las técnicas de balanceo no mejoraron el rendimiento real en ningún modelo: SMOTE, ADASYN y class weights dispararon el recall hacia valores cercanos a 1.0, pero a costa de una precisión tan baja que haría inoperativo cualquier sistema de alertas en producción. La estrategia sin balanceo ganó consistentemente en PR-AUC test en todos los modelos, evidenciando que los datos contienen señal suficiente para que los modelos aprendan los patrones de fraude sin necesidad de intervención artificial sobre la distribución.</p>
<p>Un aspecto que merece atención particular es el ROC-AUC de 0.9998 obtenido por XGBoost, valor que podría interpretarse como una señal de sobreajuste o fuga de datos. Sin embargo, estevalor fue validado y es técnicamente legítimo por tres razones. Primero, la diferencia entre el ROC-AUC en validación cruzada (0.9998) y en test (0.9998) es prácticamente nula, lo que descarta sobreajuste. Segundo, al reentrenar el modelo excluyendo las variables frecuencia y pais_destino, el ROC-AUC cayó a 0.95, confirmando que no existe ninguna variable que individualmente determine el target, es decir, no hay fuga de datos. Tercero, el valor se mantiene estable independientemente de la técnica de balanceo aplicada (sin balanceo: 0.9998, SMOTE: 0.9997, ADASYN: 0.9997, weights: 0.9997), lo que indica que el modelo aprendió patrones reales y no artefactos del proceso de entrenamiento. La explicación de fondo es que el dataset histórico presenta una estructura de clases muy marcada: el 100% de los fraudes se concentra en frecuencia H y todos tienen como destino el país W0, creando fronteras de decisión muy claras que cualquier modelo de árboles captura con alta precisión. El ROC-AUC de 0.9998 significa que si se toma al azar una transacción fraudulenta y una legítima, el modelo asigna mayor probabilidad de fraude a la correcta en el 99.98% de los pares posibles, lo cual es una consecuencia directa de la estructura del dato y no una anomalía del modelo. El riesgo asociado es que si en producción el fraude migra hacia otras frecuencias o países destino distintos a W0, el modelo podría degradarse, por lo que se recomienda monitoreo mensual de la distribución de estas variables como señal de alerta para reentrenamiento.</p>
<p>XGBoost sin balanceo fue seleccionado como el modelo final a pesar de presentar un PR-AUC en test de 0.9522, ligeramente inferior al de Random Forest (0.9659). Esta decisión se fundamenta en que la diferencia en el ROC-AUC entre ambos modelos resultó estadísticamente no significativa (p=0.922), lo que indica un rendimiento predictivo comparable. Sin embargo, XGBoost ofrece una ventaja competitiva crítica para el despliegue en producción: su eficiencia computacional. Mientras que Random Forest requirió 535.3 segundos para su ejecución, XGBoost completó el proceso en solo 55.8 segundos, siendo casi diez veces más rápido. Por su parte, Naive Bayes (PR-AUC 0.1864) y LinearSVC (0.6844) fueron descartados debido a un desempeño significativamente inferior, confirmado mediante pruebas de bootstrap (p=0.000).</p>
<p>El análisis de explicabilidad con LIME reveló que el fraude está determinado principalmente por combinaciones de país de destino (especialmente pais_destino_W0) y tipo de transacción (tipo_trx_CP0), con la frecuencia horaria como señal secundaria, siendo el monto una variable de menor peso relativo. Este patrón fue consistente entre Random Forest y XGBoost de forma independiente, lo que otorga alta credibilidad al hallazgo y abre la posibilidad de implementar reglas geográficas complementarias como primera capa de detección rápida antes de invocar el modelo completo.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="análisis-exploratorio-bivariado.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conclusión-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/02-modelo.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["eda_payments.pdf", "eda_payments.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
